/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.*;
import ENTITY.Materia;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author IVÁN UTRIA
 */
public class Ppal extends javax.swing.JFrame {

    Proceso proceso;
    int xMouse,yMouse;
    
    public Ppal(){
        initComponents();
        
        tabla.setDefaultRenderer(Object.class, new ImgTabla());
        
        tabla.getTableHeader().setEnabled(false);
        tabla.getTableHeader().setOpaque(false);
        tabla.setRowHeight(25);
        tabla.getTableHeader().setBackground(new Color(45, 161, 132));
        tabla.getTableHeader().setForeground(new Color(236, 240, 241));
        
        proceso = new Proceso();
        Actualizar();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/IMG/path10-6.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCreditos = new javax.swing.JTextField();
        lblAgregar = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        txtMateria = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(47, 61, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(47, 61, 80));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel3.setLayout(null);

        btnMinimizar.setBackground(new java.awt.Color(47, 61, 80));
        btnMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/minimizar.png"))); // NOI18N
        btnMinimizar.setToolTipText("Minimizar");
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.setOpaque(true);
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });
        jPanel3.add(btnMinimizar);
        btnMinimizar.setBounds(50, 0, 50, 30);

        btnCerrar.setBackground(new java.awt.Color(47, 61, 80));
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cerrar.png"))); // NOI18N
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        jPanel3.add(btnCerrar);
        btnCerrar.setBounds(100, 0, 50, 30);

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel6.setBackground(new java.awt.Color(47, 61, 80));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel6.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setText("CProm");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel1);
        jLabel1.setBounds(10, 0, 50, 30);

        jPanel1.add(jPanel6, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        lblTotal.setBackground(new java.awt.Color(47, 61, 80));
        lblTotal.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(47, 61, 80));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0");
        lblTotal.setMaximumSize(new java.awt.Dimension(500, 100));
        lblTotal.setPreferredSize(new java.awt.Dimension(250, 100));
        jPanel2.add(lblTotal, java.awt.BorderLayout.EAST);

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel4.setLayout(null);

        txtCreditos.setBackground(new java.awt.Color(240, 240, 240));
        txtCreditos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCreditos.setForeground(new java.awt.Color(47, 61, 80));
        txtCreditos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCreditos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 61, 80)), "*Número de Creditos", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 10), new java.awt.Color(47, 61, 80))); // NOI18N
        txtCreditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCreditosKeyPressed(evt);
            }
        });
        jPanel4.add(txtCreditos);
        txtCreditos.setBounds(420, 15, 180, 40);

        lblAgregar.setBackground(new java.awt.Color(74, 148, 218));
        lblAgregar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(236, 240, 241));
        lblAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar.setText("AGREGAR");
        lblAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 61, 80)));
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.setOpaque(true);
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAgregarMouseExited(evt);
            }
        });
        jPanel4.add(lblAgregar);
        lblAgregar.setBounds(620, 21, 180, 30);

        txtNota.setBackground(new java.awt.Color(240, 240, 240));
        txtNota.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNota.setForeground(new java.awt.Color(47, 61, 80));
        txtNota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNota.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 61, 80)), "*Nota", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 10), new java.awt.Color(47, 61, 80))); // NOI18N
        jPanel4.add(txtNota);
        txtNota.setBounds(220, 15, 180, 40);

        txtMateria.setBackground(new java.awt.Color(240, 240, 240));
        txtMateria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtMateria.setForeground(new java.awt.Color(47, 61, 80));
        txtMateria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMateria.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 61, 80)), "Materia", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 10), new java.awt.Color(47, 61, 80))); // NOI18N
        txtMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel4.add(txtMateria);
        txtMateria.setBounds(20, 15, 180, 40);
        jPanel4.add(jSeparator1);
        jSeparator1.setBounds(20, 70, 780, 10);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setMinimumSize(new java.awt.Dimension(500, 280));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return columna==5;
            }
        };
        tabla.setBackground(new java.awt.Color(128, 140, 141));
        tabla.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabla.setForeground(new java.awt.Color(236, 240, 241));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"e", "3", "3", "3"},
                {"t", "6", "6", "6"},
                {"r", "5", null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setGridColor(new java.awt.Color(12, 121, 190));
        tabla.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabla.setOpaque(false);
        tabla.setRowHeight(40);
        tabla.setSelectionBackground(new java.awt.Color(128, 140, 141));
        tabla.setShowHorizontalLines(false);
        tabla.setShowVerticalLines(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 540, 270));

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(820, 412));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        Guardar();
        txtMateria.requestFocus();
    }//GEN-LAST:event_lblAgregarMouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        Seleccion();
    }//GEN-LAST:event_tablaMouseClicked

    private void txtCreditosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditosKeyPressed
        if(evt.getKeyCode() == 10){
            Guardar();
            txtMateria.requestFocus();
        }
    }//GEN-LAST:event_txtCreditosKeyPressed

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        btnCerrar.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        btnCerrar.setBackground(new Color(47, 61, 80));
    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        btnMinimizar.setBackground(new Color(51, 67, 86));
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        btnMinimizar.setBackground(new Color(47,61,80));
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen()-xMouse;
        int y = evt.getYOnScreen()-yMouse;  
        if (x<0 && y>0) {
            this.setLocation(0,y);
        }else{
            if (y<0 && x>0) {
                this.setLocation(x,0);
            }
            else{
                if(x<0 && y<0){
                    this.setLocation(0,0);
                }
                else{
                    this.setLocation(x,y);
                }
            }
        }
        if (x<0 && y>0) {
            this.setLocation(0,y);
        }else{
            if (y<0 && x>0) {
                this.setLocation(x,0);
            }
            else{
                if(x<0 && y<0){
                    this.setLocation(0,0);
                }
                else{
                    this.setLocation(x,y);
                }
            }
        }
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void lblAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseEntered
        lblAgregar.setBackground(new Color(60, 125, 184));
    }//GEN-LAST:event_lblAgregarMouseEntered

    private void lblAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseExited
        lblAgregar.setBackground(new Color(74, 148, 218));
    }//GEN-LAST:event_lblAgregarMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked
    
    private void Reestablecer(){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea Eliminar todo?")==0) {
            proceso.Reset(tabla.getRowCount());
            Actualizar();
        }
    }
    
    private void Seleccion(){
        if(tabla.getSelectedColumn()==4){
             if (JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea Quitar?")==0) {
                proceso.Quitar(tabla.getSelectedRow());
                Actualizar();
            }
        }
    }
    
    private void Guardar(){
        if (new Validaciones().Validar(txtCreditos.getText(), txtNota.getText())) {
            Materia materia = new Materia();
            materia.setNMateria(txtMateria.getText().toUpperCase());
            materia.setNota(Float.parseFloat(txtNota.getText()));
            materia.setCreditos(Integer.parseInt(txtCreditos.getText()));
            proceso.Guardar(materia);
            Actualizar();
            Limpiar();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Verifique que la nota y numero de creditos esten correctamente digitados");
        }
    }
    
    private void Limpiar(){
        txtCreditos.setText("");
        txtMateria.setText("");
        txtNota.setText("");
    }
    
    private void Actualizar(){
        float prom = proceso.Promedio();
        if (prom<3.0) {
            lblTotal.setForeground(new Color(225, 77, 65));
        }else{
            if (prom>=3.0 && prom <=3.9) {
                lblTotal.setForeground(new Color(60, 125, 184));
            }else{
                if (prom>=4) {
                    lblTotal.setForeground(new Color(45, 161, 132));
                }
            }
        }
        tabla.setModel(proceso.Materias());
        lblTotal.setText(String.valueOf(proceso.Promedio()));
    }
    
//    private int total(float p){
//        //return (p==0 "0" : String.valueOf(p);
//        if (p==0) {
//            return 0;
//        }else{
//            return Integer.parseInt(p);
//        }
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ppal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCreditos;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables

    
}
